### PR TITLE
Don't fail delete if the resource group does not exist

### LINKED ISSUE #256: Some create failure types make deleting the cluster impossible
If some cluster elements are missing (never created or deleted in previous failed delete attempt or deleted by customer) deletion will fail and not clean all resources/delete cluster from DB.  And the clusters will not be able to be deleted by any means available to the customer.

### PR DESCRIPTION
**Pull request by asalkeld**
closes #256

### CODE REVIEW

File: pkg/backend/openshiftcluster/delete.go [hunk 1]
```diff
@@ -88,7 +88,7 @@ func (m *Manager) Delete(ctx context.Context) error {
 	m.log.Printf("deleting resource group %s", resourceGroup)
 	err = m.groups.DeleteAndWait(ctx, resourceGroup)
 	if detailedErr, ok := err.(autorest.DetailedError); ok &&
-		detailedErr.StatusCode == http.StatusForbidden {
+		detailedErr.StatusCode == http.StatusForbidden || detailedErr.StatusCode == http.StatusNotFound {
```
Comment (jim-minter) [inline pkg/backend/openshiftcluster/delete.go]:
```suggestion
		(detailedErr.StatusCode == http.StatusForbidden || detailedErr.StatusCode == http.StatusNotFound) {
```

^ isn't the above necessary due to operator precedence?

Comment (m1kola) [reply pkg/backend/openshiftcluster/delete.go]: Good catch! I didn't notice &&!
