### PR TITLE
Do not run enrichment in some provisioning states

### LINKED ISSUE #389: invalid configuration in enrichOne
Saw the following RP error in eastus2 (you can check Jarvis if needed):
"invalid configuration: no configuration has been provided" at clusterdata.go:71

I think we got an incoming GET on the cluster when it was being created, before the kubeadmin was in place.

I think the fix is that enrichment should not take place if the cluster is in state Creating or Failed/Creating, probably not Deleting or Failed/Deleting as well.

### PR DESCRIPTION
**Pull request by m1kola**
Fixes #389

### CODE REVIEW

File: pkg/util/clusterdata/clusterdata.go [hunk 1]
```diff
@@ -117,6 +121,26 @@ out:
 	}
 }
 
+// isValidProvisioningState checks whether or not it is ok to run enrichment
```
Comment (mjudeikis) [inline pkg/util/clusterdata/clusterdata.go:124]: Should we run this only if the cluster is in Successful state? It can be failed due to `Updating` and `AdminUpdating` too. And we might be safer doing this only on "Successful cluster". On top of that logic would become much cleaner and transparent in API model:

```
// IsTerminal returns true if state is Terminal
func (t ProvisioningState) IsSucceeded() bool {
	return ProvisioningStateSucceeded == t
}
```

And when customer comes to us, we have one and single answer - cluster if in a failed state. As now it gets a little bit confusing when it runs and when it does not.

Comment (m1kola) [reply pkg/util/clusterdata/clusterdata.go:124]: If decide to run enrichment only in `ProvisioningStateSucceeded` - we will be reporting invalid state of worker profiles, version, etc to a customer during the update.

Also in the failed `AdminUpdating` and `Updating` states a customer can have a healthy cluster and it will be confusing that the cluster works fine, but RP does not report worker profiles, for example.

Comment (mjudeikis) [reply pkg/util/clusterdata/clusterdata.go:124]: I get the consequence, but Im thinking of all the confusion it might create why sometimes it works and sometimes it does not... Might be a small price to pay

Comment (mjudeikis) [reply pkg/util/clusterdata/clusterdata.go:124]: On the other hand, 
I scale up cluster. And It failed. I want to check what is the current state, how much it managed to scale before failing. 
Complex...

Comment (jim-minter) [reply pkg/util/clusterdata/clusterdata.go:124]: I am +1 on how this PR is implemented currently.  In the future I want us to cache the last enriched output, that will help with the Deleting/Failed-Deleting phases.

File: pkg/util/clusterdata/clusterdata.go [hunk 2]
```diff
@@ -117,6 +121,26 @@ out:
...
+// of the object based on the ProvisioningState.
+// For example, when a user creates a new cluster kubeconfig for the cluster
+// will be missing from the object in the beginning of the creation process
+// and it will be not possible to make requests to the API server.
+func (e *bestEffortEnricher) isValidProvisioningState(oc *api.OpenShiftCluster) bool {
+	switch oc.Properties.ProvisioningState {
+	case api.ProvisioningStateCreating, api.ProvisioningStateDeleting:
+		e.log.Infof("cluster is in %q provisioning state. Skiping enrichment...", oc.Properties.ProvisioningState)
```
Comment (jim-minter) [inline pkg/util/clusterdata/clusterdata.go:132]:
```suggestion
		e.log.Infof("cluster is in %q provisioning state. Skipping enrichment...", oc.Properties.ProvisioningState)
```

File: pkg/util/clusterdata/clusterdata.go [hunk 3]
```diff
@@ -117,6 +121,26 @@ out:
...
+		return false
+	case api.ProvisioningStateFailed:
+		switch oc.Properties.FailedProvisioningState {
+		case api.ProvisioningStateCreating, api.ProvisioningStateDeleting:
+			e.log.Infof("cluster is in failed %q provisioning state. Skiping enrichment...", oc.Properties.ProvisioningState)
```
Comment (jim-minter) [inline pkg/util/clusterdata/clusterdata.go:137]:
```suggestion
			e.log.Infof("cluster is in failed %q provisioning state. Skipping enrichment...", oc.Properties.ProvisioningState)
```
